version: '3.8'

services:
  # DApp Rankings API
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tasmil_finance
      - CORS_ORIGIN=http://localhost:3000
      - LOG_LEVEL=info
      - PORT=4000
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - dapp-network

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=tasmil_finance
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sample-data.sql:/docker-entrypoint-initdb.d/sample-data.sql
    restart: unless-stopped
    networks:
      - dapp-network

  # pgAdmin (optional - for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - dapp-network

volumes:
  postgres_data:

networks:
  dapp-network:
    driver: bridge 